// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB2-Z2PAAb0yBIjOc2yok_h8L_0jNd9XA',
    appId: '1:740790213926:web:c7044098b7477ff8d2b5e7',
    messagingSenderId: '740790213926',
    projectId: 'mynotes-179ed',
    authDomain: 'mynotes-179ed.firebaseapp.com',
    storageBucket: 'mynotes-179ed.appspot.com',
    measurementId: 'G-FZPNS9Q32C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1BAWl1UxlSkqlFqFoc3gebEjmLpdsFOY',
    appId: '1:740790213926:android:b2f127324068c8aad2b5e7',
    messagingSenderId: '740790213926',
    projectId: 'mynotes-179ed',
    storageBucket: 'mynotes-179ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj0jNsooURJwR7zKvwZSNMAJMlSoysPYA',
    appId: '1:740790213926:ios:36a394d82580adadd2b5e7',
    messagingSenderId: '740790213926',
    projectId: 'mynotes-179ed',
    storageBucket: 'mynotes-179ed.appspot.com',
    iosClientId: '740790213926-1ktsjmruh5lbdqkvnamrbfqqqu0114ap.apps.googleusercontent.com',
    iosBundleId: 'com.cursoflutter.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj0jNsooURJwR7zKvwZSNMAJMlSoysPYA',
    appId: '1:740790213926:ios:073eaedee707cdacd2b5e7',
    messagingSenderId: '740790213926',
    projectId: 'mynotes-179ed',
    storageBucket: 'mynotes-179ed.appspot.com',
    iosClientId: '740790213926-3ecdt22cujj7aq61mst74uougjh6e55q.apps.googleusercontent.com',
    iosBundleId: 'com.cursoflutter.mynotes.RunnerTests',
  );
}
